### ISSUE TITLE
[Bug]: Windows 10 按照教程操作不能正常启动

### ISSUE THREAD

**Issue by Wolf1329** [OreosLab/SSRSpeedN#1]
### 预期情况

正常运行

### 实际情况

![image](https://user-images.githubusercontent.com/21032366/188188008-07711050-a590-4247-b777-9efb8e4b8717.png)

### 复现方法

Windows 10 21H2 19044.1889
点击ssrspeed.bat 或者命令执行该脚本

### 日志信息

C:\Users\admin\Downloads\telerik\temp\SSRSpeedN-1.1.1>C:\Users\admin\Downloads\telerik\temp\SSRSpeedN-1.1.1\bin\ssrspeed.bat
'当前权限' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'to' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'）' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ER' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ho' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'--include-group' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'Skip' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
无效参数 - Remark
't' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'emark' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'URL' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'手动设置组。' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'on' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'B_PAGE_SIMULATION' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'SPEED_TEST_NET' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'接（不可留空）:' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'滞ü⑹蜕秆〗诘?' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'设置颜色' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'喜慌判颍缒锨胩?' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'else' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'jx1' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'jx2' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
此时不应有 &。

### 我确认已更新至最新版本

- [ ] 是

### 我确认已查询历史 issues

- [ ] 是

**Comment by Oreomeow** [comment]
你好，请检查下文件编码，可以按下图另存一下文件

![image](https://user-images.githubusercontent.com/85870818/188192114-d230e9bf-6578-492c-b78d-366eabaac553.png)

**Comment by Wolf1329** [comment]
感谢大佬&nbsp;这么晚了还在线回复&nbsp;
已按你的方式来操作还是一样









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OreosLab/SSRSpeedN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月2日(星期五) 晚上11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OreosLab/SSRSpeedN] [Bug]: Windows 10 按照教程操作不能正常启动 (Issue #1)





 
你好，请检查下文件编码，可以按下图另存一下文件

**Comment by Wolf1329** [comment]
![image](https://user-images.githubusercontent.com/21032366/188195813-810872fb-62f2-48a9-9af9-0162693ba339.png)

**Comment by Oreomeow** [comment]
> ![image](https://user-images.githubusercontent.com/21032366/188195813-810872fb-62f2-48a9-9af9-0162693ba339.png)

已了解错误原因，我 vscode 设置默认提交将 windows 换行 `CRLE` 自动转换为 unix `LF` 导致了错误，该错误下次修正。

解决方法：
点击 Notepad++ 右下角 `LF` 转换为 `CRLE` 或 `CR` 即可。

**Comment by Wolf1329** [comment]
感谢大佬指点
