### ISSUE TITLE
[Help wanted]: 新版本流媒体大多测不出来

### ISSUE THREAD

**Issue by lrs95** [OreosLab/SSRSpeedN#18]
### 操作系统

Windows

### 实际情况

新版本测出来是这种情况，下载速度没问题，就是流媒体大多测不出来，1.1.1版可以测，1.2.3版显示 Geo IP reset
![image](https://user-images.githubusercontent.com/24587454/189472463-ff7dffc2-9b5d-4553-8832-19919ce3b9eb.png)
![image](https://user-images.githubusercontent.com/24587454/189472476-75b7946b-5788-45ff-9aab-958bad3ac513.png)

### 复现方法

1

### 日志信息

1

### 我确认已更新至最新版本

- [x] 是

### 我确认已查询历史 issues

- [x] 是

**Comment by Mashiro2000** [comment]
目前项目的逻辑是先测试geo_ip，如果报错，就不测速流媒体，以上逻辑在同步代码无异常，但放在异步代码中，由于速度太快，访问geo_ip过于频繁，导致报错，等等修改代码逻辑

**Comment by Oreomeow** [comment]
之后可能会取消 geo_ip 和流媒体之间的逻辑关系

**Comment by Mashiro2000** [comment]
你现在可以再试试看，逻辑已更新

**Comment by lrs95** [comment]
> 你现在可以再试试看，逻辑已更新

上一版的GeoLite2-City.mmdb还需要吗

**Comment by Oreomeow** [comment]
> > 你现在可以再试试看，逻辑已更新
> 
> 上一版的GeoLite2-City.mmdb还需要吗

需要的，正在推新版，稍等

**Comment by lrs95** [comment]
> > > 你现在可以再试试看，逻辑已更新
> > 
> > 
> > 上一版的GeoLite2-City.mmdb还需要吗
> 
> 需要的，正在推新版，稍等；还有配置文件也需要更新

正在测试中，不过我在设置里speed已经改成false了为什么还会测速呢
![image](https://user-images.githubusercontent.com/24587454/189493154-c71df338-8134-40d3-a970-ab289ede0ea2.png)
![image](https://user-images.githubusercontent.com/24587454/189493166-208bcb74-6102-4c9a-b485-581e238b75fb.png)

**Comment by Oreomeow** [comment]
@lrs95 忘加自定义测试模式了，现在默认全测试，白天处理

**Comment by lrs95** [comment]
> @lrs95忘记加自定义测试模式，现在默认全测试测试处理模式了

嗯嗯，我测完了，65个节点测了31分钟，跟1.1.1版时间差不多，不过现在都正常了，之前1.1.1是没测下载速度，这次是全测，不过算上下载速度测试时间的话比之前是要快些了，主要还是maxConnections设置的1，如果支持并发应该快更多。等白天修复自定义测试模式再试试。
![image](https://user-images.githubusercontent.com/24587454/189494609-1059ce75-c2c9-4d8c-a93d-6006551cdf43.png)

**Comment by lrs95** [comment]
还有这个奈飞解锁测试我感觉有点不准跟之前比，我用圈X的奈飞解锁测了下自制和非自制一半一半吧，这里测试除了KR那两个其它节点显示全解锁。

**Comment by Oreomeow** [comment]
1. 已更新 1.3.1 版本
2. 流媒体解锁受时效性影响较大

**Comment by Mashiro2000** [comment]
> 还有这个奈飞解锁测试我感觉有点不准跟之前比，我用圈X的奈飞解锁测了下自制和非自制一半一半吧，这里测试除了KR那两个其它节点显示全解锁。

bug已处理，系代码逻辑错误造成的，现在可以去测试下，有问题再反馈
