### ISSUE TITLE
[Bug]: 我用订阅转换后的clash订阅出现会出现Geo IP Reset的情况

### ISSUE THREAD

**Issue by lrs95** [OreosLab/SSRSpeedN#29]
### 预期情况

1

### 实际情况

1、[，](https://sub.xeton.dev/sub?target=clash)这是订阅转换后的链接的前半段，把链接里的target参数改成v2ray就正常了，如果是clash就会出现Geo IP Reset的情况
2、还有个情况就是在某个节点的某一项没测通的时候会出现卡很久的情况

### 复现方法

1

### 日志信息

1

### 额外信息

最新1.3.4版本

### 我确认已更新至最新版本

- [x] 是

### 我确认已查询历史 issues

- [x] 是

**Comment by Oreomeow** [comment]
1. 可通过修改 `ssrspeed.json` 配置 `maxConnections` 或命令行参数

  - `ssrspeed.json`
    
    ```diff
    - "maxConnections": 50,
    + "maxConnections": 1,
    ```

  - 命令行参数

    ```
    -mc MAX_CONNECTIONS, --max-connections=MAX_CONNECTIONS

                          最大连接数。某些机场不支持并发连接，可设置为 1.
    ```

2. 取决于节点质量，可选用 `stream` 或 `ping` 测试模式，或在 `ssrspeed.json` 中关闭某些测试项来缩短时间。

**Comment by lrs95** [comment]
> 

设置的是1，好像就是clash订阅有这问题，v2ray没问题，换了下其他机场订阅转换成clash又可以，我也不清楚是哪有问题了

**Comment by Oreomeow** [comment]
@lrs95 Geo IP Reset 只影响 Outbound Geo 测试结果

**Comment by lrs95** [comment]
> @lrs95 Geo IP Reset 只影响 Outbound Geo 测试结果

![image](https://user-images.githubusercontent.com/24587454/189639722-dc3212a7-daef-42af-acb6-319fd506e2a2.png)
