### ISSUE TITLE
[Help wanted]: Abema测试出现ssl错误

### ISSUE THREAD

**Issue by lrs95** [OreosLab/SSRSpeedN#36]
### 操作系统

Windows

### 实际情况

[BREOR][st_stream. py.148]: Abema exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ss1.c:997)

使用的1.4.5版本，测试1.4.2也有这情况，其他版本不清楚

![image](https://user-images.githubusercontent.com/24587454/190584520-61afa5de-5abb-4df2-ae68-a408c913e02a.png)

### 复现方法

测试所有节点都有这个，不知道是不是测试网址失效了

### 日志信息

无

### 我确认已更新至最新版本

- [x] 是

### 我确认已查询历史 issues

- [x] 是

**Comment by Oreomeow** [comment]
预料异常之内
